name: ML TRAINING PIPELINE

on:
  push:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/checkout@v5
        with:
          python-version: '3.12'

      - name: install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: run python
        run: |
          python train.py

      - name: build docker
        run: |
          docker build -t ml-api .

        