name: ML PIPELINE

on:
  push:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: run python
        run: |
          python train.py

      - name: build docker immage
        run: |
         docker build -t ml-api .